services:
  plemperer:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DATA_DIR=/app/data  # Optional: customize data directory path
    restart: unless-stopped